name: Pull Request Action
on:
  push:
    paths:
      - '*.py'
  pull_request:
    paths:
      - '*.py'
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Python
        uses: actions/setup-python@v5 # Action to set up Python
        with:
          python-version: '3.9.21' # Specify your desired Python version

      - name: Install tools
        run: pip install black isort flake8

      - name: Run black
        uses: psf/black@stable
        with:
          options: "--line-length 80"
          src: "backend/src"

      - name: Run isort
        uses: isort/isort-action@master
        with:
            configuration: "--profile black"
            sort-paths: "backend/src"

      - name: Run flake8
        uses: py-actions/flake8@v2 # Action to run flake8
        with:
          # Optional: Specify flake8 options or plugins here
          # flake8_args: "--max-line-length=80"
          # plugins: "flake8-black"
          max-line-length: "80"
          path: "backend/src"
      