name: Pull Request Action
on:
  push:
    paths:
      - '*.py'
  pull_request:
    paths:
      - '*.py'
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Python
        uses: actions/setup-python@v5 # Action to set up Python
        with:
          python-version: '3.9.21' # Specify your desired Python version

      - name: Install tools
        run: pip install -r backend/src/requirements.txt
      - name: Run black
        run: black --check --verbose --line-length 80 backend/src

      - name: Run isort
        run: isort --check --verbose --profile black backend/src

      - name: Run flake8
        run: flake8 --max-line-length=80 backend/src
      
      - name: Run mypy
        run: mypy --ignore-missing-imports backend/src
      
      - name: Run pytest
        run: PYTHONPATH=backend/src pytest --cov=backend/src backend/tests
      